openapi: '3.0.2'
info:
  title: study-record-api
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: localhost
  - url: https://xxx.xxx
    description: production
paths:
  /study:
    get:
      summary: Get study all records
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/StudyRecord'
components:
  schemas:
    StudyRecord:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
